"use client";
import { useEffect, useMemo, useState } from "react";
import { sampleRows } from "../data/sample-data";

const seedUsers=[
  {name:"Chris Vieux",email:"cvieux@kannonmfg.com",role:"Administrator",status:"Active",last:"Today"},
  {name:"Demo Buyer",email:"buyer@kannonmfg.com",role:"Purchasing",status:"Active",last:"Yesterday"},
  {name:"Demo Manager",email:"manager@kannonmfg.com",role:"Viewer",status:"Pending",last:"Never"}
];
const today=new Date("2026-08-02T12:00:00-05:00");
const days=d=>Math.ceil((new Date(`${d}T12:00:00`)-today)/86400000);
const riskOf=r=>r.expected_arrival&&new Date(r.expected_arrival)>new Date(r.due_date)?"Past Due":days(r.due_date)<0?"Past Due":!r.expected_arrival||days(r.due_date)<=7?"At Risk":"On Track";

export default function SundayPrototype(){
  const [signedIn,setSignedIn]=useState(false);
  const [page,setPage]=useState("dashboard");
  const [rows,setRows]=useState(sampleRows);
  const [users,setUsers]=useState(seedUsers);
  const [search,setSearch]=useState("");
  const [customer,setCustomer]=useState("all");
  const [risk,setRisk]=useState("all");
  const [owner,setOwner]=useState("all");
  const [edit,setEdit]=useState(null);
  const [invite,setInvite]=useState(false);
  const [toast,setToast]=useState("");
  const [lastRefresh,setLastRefresh]=useState("August 2, 2026 at 10:00 AM");
  useEffect(()=>{try{const u=localStorage.getItem("kannonPrototypeUsers");const r=localStorage.getItem("kannonPrototypeRows");if(u)setUsers(JSON.parse(u));if(r)setRows(JSON.parse(r));}catch{}},[]);
  const notify=msg=>{setToast(msg);setTimeout(()=>setToast(""),3200)};
  const saveRows=next=>{setRows(next);localStorage.setItem("kannonPrototypeRows",JSON.stringify(next));};
  const saveUsers=next=>{setUsers(next);localStorage.setItem("kannonPrototypeUsers",JSON.stringify(next));};
  const customers=useMemo(()=>[...new Set(rows.map(r=>r.customer))].sort(),[rows]);
  const filtered=useMemo(()=>rows.filter(r=>(customer==="all"||r.customer===customer)&&(risk==="all"||riskOf(r)===risk)&&(owner==="all"||r.owner===owner)&&JSON.stringify(r).toLowerCase().includes(search.toLowerCase())),[rows,customer,risk,owner,search]);
  if(!signedIn)return <Login onSignIn={()=>setSignedIn(true)}/>;
  return <div className="shell">
    <header className="topbar"><div className="brand">KANNON MFG</div><nav className="nav"><button className={page==="dashboard"?"active":""} onClick={()=>setPage("dashboard")}>Dashboard</button><button className={page==="admin"?"active":""} onClick={()=>setPage("admin")}>Administration</button></nav><div className="top-actions"><div className="avatar">CV</div><div className="user-menu"><b>Chris Vieux</b><span>Administrator</span></div><button className="btn top-signout" onClick={()=>setSignedIn(false)}>Sign out</button></div></header>
    <main className="content">{page==="dashboard"?<Dashboard rows={rows} filtered={filtered} customers={customers} search={search} setSearch={setSearch} customer={customer} setCustomer={setCustomer} risk={risk} setRisk={setRisk} owner={owner} setOwner={setOwner} lastRefresh={lastRefresh} refresh={()=>{setLastRefresh(new Date().toLocaleString("en-US",{timeZone:"America/Chicago",dateStyle:"long",timeStyle:"short"}));notify("SharePoint refresh simulated successfully — 21 active orders found.")}} onEdit={setEdit}/>:<Admin users={users} onInvite={()=>setInvite(true)} onToggle={i=>{const n=[...users];n[i]={...n[i],status:n[i].status==="Disabled"?"Active":"Disabled"};saveUsers(n);notify(`${n[i].name} is now ${n[i].status}`)}} onRemove={i=>{if(users[i].email==="cvieux@kannonmfg.com")return notify("The primary administrator cannot be removed.");saveUsers(users.filter((_,x)=>x!==i));notify("User removed")}}/>}</main>
    {edit&&<EditModal row={edit} onClose={()=>setEdit(null)} onSave={updated=>{saveRows(rows.map(r=>r.id===updated.id?updated:r));setEdit(null);notify(`${updated.work_order} updated`)}}/>}
    {invite&&<InviteModal onClose={()=>setInvite(false)} onSave={u=>{saveUsers([...users,u]);setInvite(false);notify(`Invitation queued for ${u.email}`)}}/>}
    {toast&&<div className="toast">{toast}</div>}
  </div>;
}

function Login({onSignIn}){return <div className="login"><section className="login-hero"><div className="brand">KANNON MFG</div><div className="hero-copy"><h1>Needs Material Dashboard</h1><p>Track material shortages, supplier commitments, expected arrivals, and production risk from one secure internal report.</p><div className="hero-points"><div className="hero-point"><span className="check">✓</span>Uses Kannon Microsoft 365 identities</div><div className="hero-point"><span className="check">✓</span>Refreshes from the SharePoint scheduler at 10:00 AM</div><div className="hero-point"><span className="check">✓</span>Role-controlled access and audit history</div></div></div><small>Baseline application — production credentials are not configured yet.</small></section><section className="login-panel"><div className="login-card"><div className="brand login-brand">KANNON MFG</div><h2>Welcome back</h2><p>Use your Kannon Microsoft account to access the Needs Material dashboard.</p><button className="ms-button" onClick={onSignIn}><span className="ms-logo"><i/><i/><i/><i/></span>Sign in with Microsoft</button><div className="demo-note"><b>Baseline mode:</b> This button signs you in locally as Chris Vieux, Administrator. Cursor will replace this authentication without changing the screen.</div></div></section></div>}

function Dashboard(p){
  const metrics=[["Open shortages",p.rows.length,"Active Need Material orders"],["Past due",p.rows.filter(r=>riskOf(r)==="Past Due").length,"Immediate attention"],["Due in 7 days",p.rows.filter(r=>days(r.due_date)>=0&&days(r.due_date)<=7).length,"Production exposure"],["No arrival date",p.rows.filter(r=>!r.expected_arrival).length,"Supplier date missing"]];
  const dueMap={};p.filtered.forEach(r=>dueMap[r.due_date]=(dueMap[r.due_date]||0)+1);const bars=Object.entries(dueMap).sort().slice(0,12);const max=Math.max(1,...bars.map(x=>x[1]));
  const counts=["Past Due","At Risk","On Track"].map(x=>[x,p.filtered.filter(r=>riskOf(r)===x).length]);const rmax=Math.max(1,...counts.map(x=>x[1]));
  return <section><div className="page-head"><div><h1>Needs Material Dashboard</h1><p>Active production orders requiring material follow-up.</p><div className="refresh-note"><span className="dot"/>Last refreshed: {p.lastRefresh}</div></div><div className="actions"><button className="btn" onClick={()=>window.print()}>Export</button><button className="btn primary" onClick={p.refresh}>Refresh Now</button></div></div>
    <div className="filters"><input className="control" placeholder="Search WO, customer, part, material, or notes" value={p.search} onChange={e=>p.setSearch(e.target.value)}/><select className="control" value={p.customer} onChange={e=>p.setCustomer(e.target.value)}><option value="all">All customers</option>{p.customers.map(x=><option key={x}>{x}</option>)}</select><select className="control" value={p.risk} onChange={e=>p.setRisk(e.target.value)}><option value="all">All risk levels</option><option>Past Due</option><option>At Risk</option><option>On Track</option></select><select className="control" value={p.owner} onChange={e=>p.setOwner(e.target.value)}><option value="all">All owners</option><option>Chris Vieux</option><option>Buyer 1</option><option>Unassigned</option></select></div>
    <div className="cards">{metrics.map(m=><div className="card" key={m[0]}><label>{m[0]}</label><strong>{m[1]}</strong><small>{m[2]}</small></div>)}</div>
    <div className="grid2"><div className="panel"><div className="panel-head"><h2>Needs Material by Due Date</h2></div><div className="panel-body"><div className="bars">{bars.map(([d,v])=><div className="barwrap" key={d}><div className="barval">{v}</div><div className="bar" style={{height:Math.max(7,v/max*155)}}/>{d.slice(5)}</div>)}</div></div></div><div className="panel"><div className="panel-head"><h2>Risk Summary</h2></div><div className="panel-body risk-list">{counts.map(([n,v])=><div className="risk-row" key={n}><b>{n}</b><div className="track"><div className={`fill ${n==="Past Due"?"red":n==="At Risk"?"amber":"green"}`} style={{width:`${v/rmax*100}%`}}/></div><b>{v}</b></div>)}</div></div></div>
    <div className="panel table-panel"><div className="panel-head"><h2>Active Needs Material</h2><span>{p.filtered.length} records shown</span></div><div className="tablewrap"><table className="table"><thead><tr>{["Risk","WO","Customer","Due Date","Part #","Description","Qty","Material Needed","Supplier / PO","Expected Arrival","Owner","Follow-Up Notes",""] .map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{p.filtered.length?p.filtered.map(r=><tr key={r.id}><td><span className={`badge ${riskOf(r).toLowerCase().replaceAll(" ","-")}`}>{riskOf(r)}</span></td><td className="mono">{r.work_order}</td><td>{r.customer}</td><td>{r.due_date}</td><td className="mono">{r.part_number}</td><td>{r.description}</td><td>{r.quantity}</td><td>{r.material_needed||<em>Not entered</em>}</td><td>{r.supplier||r.material_po||<em>Not entered</em>}</td><td>{r.expected_arrival||<em>Missing</em>}</td><td>{r.owner}</td><td>{r.follow_up_notes||"—"}</td><td><button className="btn" onClick={()=>p.onEdit({...r})}>Edit</button></td></tr>):<tr><td colSpan="13" className="empty">No matching records.</td></tr>}</tbody></table></div></div>
  </section>;
}

function Admin({users,onInvite,onToggle,onRemove}){return <section><div className="page-head"><div><h1>Administration</h1><p>Manage dashboard users and their access.</p></div><div className="actions"><button className="btn primary" onClick={onInvite}>Invite User</button></div></div><div className="admin-grid"><div className="panel table-panel"><div className="panel-head"><h2>Authorized Users</h2><span>{users.length} users</span></div><div className="tablewrap"><table className="table users-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Last Login</th><th>Actions</th></tr></thead><tbody>{users.map((u,i)=><tr key={u.email}><td><b>{u.name}</b><br/><span className="muted">{u.email}</span></td><td><span className="role">{u.role}</span></td><td><span className={`status ${u.status==="Pending"?"pending":""}`}>{u.status}</span></td><td>{u.last}</td><td><button className="btn" onClick={()=>onToggle(i)}>{u.status==="Disabled"?"Enable":"Disable"}</button> <button className="btn danger" onClick={()=>onRemove(i)}>Remove</button></td></tr>)}</tbody></table></div></div><aside className="side-card"><h3>How access works</h3><ol><li>You invite a Kannon employee.</li><li>Their Microsoft 365 email is added to the allowlist.</li><li>They sign in with Microsoft.</li><li>The dashboard applies the role you assigned.</li></ol></aside></div></section>}

function EditModal({row,onClose,onSave}){const [v,setV]=useState(row);return <div className="modal-back"><div className="modal"><div className="modal-head"><h2>Edit {row.work_order}</h2><button className="x" onClick={onClose}>×</button></div><div className="modal-body"><Field label="Material Needed" value={v.material_needed} set={x=>setV({...v,material_needed:x})}/><Field label="Supplier" value={v.supplier} set={x=>setV({...v,supplier:x})}/><Field label="Material PO" value={v.material_po} set={x=>setV({...v,material_po:x})}/><Field label="Expected Arrival" type="date" value={v.expected_arrival} set={x=>setV({...v,expected_arrival:x})}/><div className="field"><label>Material Status</label><select value={v.material_status} onChange={e=>setV({...v,material_status:e.target.value})}>{["Not ordered","Quote requested","PO issued","Supplier confirmed","In transit","Partially received","Received","Problem / escalation"].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Owner</label><select value={v.owner} onChange={e=>setV({...v,owner:e.target.value})}><option>Chris Vieux</option><option>Buyer 1</option><option>Unassigned</option></select></div><div className="field"><label>Follow-Up Notes</label><textarea value={v.follow_up_notes} onChange={e=>setV({...v,follow_up_notes:e.target.value})}/></div></div><div className="modal-foot"><button className="btn" onClick={onClose}>Cancel</button><button className="btn primary" onClick={()=>onSave(v)}>Save</button></div></div></div>}
function Field({label,value,set,type="text"}){return <div className="field"><label>{label}</label><input type={type} value={value||""} onChange={e=>set(e.target.value)}/></div>}
function InviteModal({onClose,onSave}){const [name,setName]=useState(""),[email,setEmail]=useState(""),[role,setRole]=useState("Purchasing");return <div className="modal-back"><div className="modal"><div className="modal-head"><h2>Invite User</h2><button className="x" onClick={onClose}>×</button></div><div className="modal-body"><Field label="Name" value={name} set={setName}/><Field label="Kannon Email" value={email} set={setEmail} type="email"/><div className="field"><label>Role</label><select value={role} onChange={e=>setRole(e.target.value)}><option>Viewer</option><option>Purchasing</option><option>Scheduler</option><option>Administrator</option></select></div></div><div className="modal-foot"><button className="btn" onClick={onClose}>Cancel</button><button className="btn primary" onClick={()=>name&&email.includes("@")&&onSave({name,email,role,status:"Pending",last:"Never"})}>Send Invitation</button></div></div></div>}
